global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: xiranet

scrape_configs:
  - job_name: xiranet
    metrics_path: /metrics
    static_configs:
      - targets: ["xiranet:9000"]
        labels:
          service: xiranet
          env: dev
